In [1]:
import pandas as pd
from models import *
from tqdm.autonotebook import tqdm
tqdm.pandas()
from torch import nn
import json
import numpy as np
import pickle
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from argparse import Namespace
from transformers import *
import torch
import matplotlib.pyplot as plt
import torch.utils.data
import torch.nn.functional as F
import argparse
from transformers.modeling_utils import * 
from fairseq.data.encoders.fastbpe import fastBPE
from fairseq.data import Dictionary
from vncorenlp import VnCoreNLP
from utils import *

In [2]:
args = Namespace(
    dict_path = "./phobert_base/dict.txt",
    config_path = "./phobert_base/config.json",
    rdrsegmenter_path = '/home/tuna/FDM/MarketSentiment/PhoBert-Sentiment-Classification/VnCoreNLP-master/VnCoreNLP-1.1.1.jar',
    pretrained_path = './phobert_base/model.bin',
    max_sequence_length = 256,
    batch_size = 24,
    accumulation_steps = 5,
    epochs = 15, # 5
    fold = 0,
    seed = 69,
    lr = 3e-6, # 3e-5
    ckpt_path = './models',
    bpe_codes = "./phobert_base/bpe.codes"
)

In [3]:
seed_everything(69)
bpe = fastBPE(args)
rdrsegmenter = VnCoreNLP(args.rdrsegmenter_path, annotators="wseg", max_heap_size='-Xmx500m') 

./phobert_base/bpe.codes


In [4]:
# Load model
config = RobertaConfig.from_pretrained(
    args.config_path,
    output_hidden_states=True,
    num_labels=1
)
print(config)
model_bert = RobertaForAIViVN.from_pretrained(args.pretrained_path, config=config)
model_bert.cuda()
tsfm = model_bert.roberta

RobertaConfig {
  "_num_labels": 1,
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0,
  "bad_words_ids": null,
  "bos_token_id": 0,
  "decoder_start_token_id": null,
  "do_sample": false,
  "early_stopping": false,
  "eos_token_id": 2,
  "eos_token_ids": 0,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "is_encoder_decoder": false,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_eps": 1e-05,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 258,
  "min_length": 0,
  "model_type": "roberta",
  "no_repeat_ngram_size": 0,
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": true,
  "output_past": true,
  "pad_token_id": 0,
  "prefix": null,
  "pr

In [5]:
# Load the dictionary  
vocab = Dictionary()
vocab.add_from_file(args.dict_path)
print(vocab.indices)

{'<s>': 0, '<pad>': 1, '</s>': 2, '<unk>': 3, ',': 4, '.': 5, 'và': 6, 'của': 7, 'là': 8, 'các': 9, 'có': 10, 'được': 11, 'trong': 12, 'cho': 13, 'đã': 14, 'với': 15, 'một': 16, 'không': 17, 'người': 18, ')': 19, '(': 20, 'những': 21, '"': 22, 'này': 23, 'để': 24, 'ở': 25, 'khi': 26, ':': 27, 'về': 28, 'năm': 29, 'đến': 30, '-': 31, 'cũng': 32, 'vào': 33, 'trên': 34, 'tại': 35, 'nhiều': 36, 'đó': 37, 'sẽ': 38, 'từ': 39, 'ra': 40, 'phải': 41, 'như': 42, 'ngày': 43, 'lại': 44, 'bị': 45, 'ông': 46, 'làm': 47, 'hơn': 48, 'việc': 49, 'còn': 50, 'nhưng': 51, 'đang': 52, 'sau': 53, 'thì': 54, 'biết': 55, 'Việt_Nam': 56, 'đi': 57, 'nước': 58, 'rất': 59, 'mới': 60, 'sự': 61, 'có_thể': 62, 'theo': 63, 'mà': 64, ';': 65, 'chỉ': 66, 'nhất': 67, 'mình': 68, 'nhà': 69, 'tôi': 70, 'trước': 71, 'lên': 72, 'con': 73, 'vẫn': 74, 'tới': 75, '2': 76, 'nên': 77, 'tháng': 78, 'Theo': 79, 'đồng': 80, 'cùng': 81, 'hai': 82, 'anh': 83, 'cao': 84, 'khác': 85, 'họ': 86, 'rằng': 87, 'bạn': 88, 'qua': 89, 'vì': 90

In [6]:
train_df = pd.read_csv('Sentiment_result1.csv')
train_df = train_df[['content', 'sentiment_final']]
train_df = train_df.rename(columns={'content':'text'})
train_df = train_df.loc[train_df['sentiment_final'].isin(['P', 'N'])]
train_df = train_df.drop_duplicates(keep='first').reset_index(drop=True)
print(train_df)
print(train_df.sentiment_final.value_counts())
train_df.to_csv('data_clean.csv', sep='#', index=False)
train_df.text = train_df.text.progress_apply(lambda x: ' '.join([' '.join(sent) for sent in rdrsegmenter.tokenize(x)]))
X_train = convert_lines(train_df, vocab, bpe,args.max_sequence_length)
print(X_train)
print(X_train.shape)
#
label_encoder = LabelEncoder() 
train_df['sentiment_final']= label_encoder.fit_transform(train_df['sentiment_final']) 
y = train_df.sentiment_final.values
print(y)

  0%|          | 0/430 [00:00<?, ?it/s]

                                                  text sentiment_final
0    Xin thông báo khi nào hết dịch Corona thì lúc ...               P
1    5 mã trắng cửa bán rồi thì FLC tí nữa thôi là ...               P
2    Hihi theo a Quyết đến hết mùa dịch chắc cũng p...               P
3    Mai tây (ETFs) nó xả hàng ROS, mà a QC còn chơ...               N
4    Art, Hai, KLF lái con chốt, a e vô đỡ thấy thư...               N
..                                                 ...             ...
425  Tin vĩ mô:.- Bộ TC gia tăng gói hỗ trợ một số ...               P
426  T2 này khả năng thoát dớp nhưng về lâu dài phe...               N
427                             Giảm thêm 700 đáy chắc               N
428  Cuối tuần ngập tràn tin xấu.Cá Mập, đội lái đã...               N
429                                Vni lên là lên !!!!               P

[430 rows x 2 columns]
P    273
N    157
Name: sentiment_final, dtype: int64


100%|██████████| 430/430 [00:00<00:00, 2404.76it/s]

[[6.3117e+04 1.3020e+03 8.8400e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 [6.3117e+04 1.3020e+03 8.8400e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 [6.3117e+04 1.3020e+03 8.8400e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [6.3117e+04 1.3020e+03 8.8400e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 [6.3117e+04 1.3020e+03 8.8400e+02 ... 6.1320e+03 7.1510e+03 2.0000e+00]
 [6.3117e+04 1.3020e+03 8.8400e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
(430, 128)
[1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1
 0 1 0 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 1 1 1 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0
 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1
 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1

In [7]:
# Creating optimizer and lr schedulers
param_optimizer = list(model_bert.named_parameters())
print(len(param_optimizer))
print('param_optimizer', param_optimizer)
no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]
print('optimizer_grouped_parameters', optimizer_grouped_parameters)
num_train_optimization_steps = int(args.epochs*len(train_df)/args.batch_size/args.accumulation_steps)
optimizer = AdamW(optimizer_grouped_parameters, lr=args.lr, correct_bias=False)  # To reproduce BertAdam specific behavior set correct_bias=False
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=100, num_training_steps=num_train_optimization_steps)  # PyTorch scheduler
scheduler0 = get_constant_schedule(optimizer)  # PyTorch scheduler

201
param_optimizer [('roberta.embeddings.word_embeddings.weight', Parameter containing:
tensor([[ 0.0472, -0.0314,  0.0343,  ...,  0.0144, -0.0032, -0.0680],
        [ 0.0186, -0.0044,  0.0190,  ...,  0.0169, -0.0055, -0.0302],
        [-0.0074, -0.0078, -0.0142,  ...,  0.0177, -0.0011,  0.0023],
        ...,
        [ 0.0374, -0.0152,  0.0123,  ...,  0.0210, -0.0214, -0.0185],
        [ 0.0266,  0.0122, -0.0232,  ...,  0.0253,  0.0002, -0.0303],
        [ 0.0106, -0.0063, -0.0064,  ...,  0.0092, -0.0129, -0.0153]],
       device='cuda:0', requires_grad=True)), ('roberta.embeddings.position_embeddings.weight', Parameter containing:
tensor([[ 0.0150, -0.0027, -0.0069,  ..., -0.0021,  0.0077,  0.0108],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0401, -0.0189, -0.0934,  ..., -0.0437,  0.0582,  0.0378],
        ...,
        [ 0.0010, -0.0455, -0.0163,  ..., -0.0149,  0.0101,  0.0913],
        [-0.0101, -0.0156,  0.0074,  ..., -0.0072, -0.0033,  0.132

optimizer_grouped_parameters [{'params': [Parameter containing:
tensor([[ 0.0472, -0.0314,  0.0343,  ...,  0.0144, -0.0032, -0.0680],
        [ 0.0186, -0.0044,  0.0190,  ...,  0.0169, -0.0055, -0.0302],
        [-0.0074, -0.0078, -0.0142,  ...,  0.0177, -0.0011,  0.0023],
        ...,
        [ 0.0374, -0.0152,  0.0123,  ...,  0.0210, -0.0214, -0.0185],
        [ 0.0266,  0.0122, -0.0232,  ...,  0.0253,  0.0002, -0.0303],
        [ 0.0106, -0.0063, -0.0064,  ...,  0.0092, -0.0129, -0.0153]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0150, -0.0027, -0.0069,  ..., -0.0021,  0.0077,  0.0108],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0401, -0.0189, -0.0934,  ..., -0.0437,  0.0582,  0.0378],
        ...,
        [ 0.0010, -0.0455, -0.0163,  ..., -0.0149,  0.0101,  0.0913],
        [-0.0101, -0.0156,  0.0074,  ..., -0.0072, -0.0033,  0.1323],
        [-0.0528,  0.0500, -0.1011,  ...,  0.0354, -0.0190,  0.1747]],
 

In [8]:
model_bert

RobertaForAIViVN(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(64001, 768, padding_idx=1)
      (position_embeddings): Embedding(258, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, 

In [9]:
if not os.path.exists(args.ckpt_path):
    os.mkdir(args.ckpt_path)

splits = list(StratifiedKFold(n_splits=5, shuffle=True, random_state=123).split(X_train, y))
for fold, (train_idx, val_idx) in enumerate(splits):
    print("Training for fold {}".format(fold))
    best_score = 0
    if fold != args.fold:
        continue
    train_dataset = torch.utils.data.TensorDataset(torch.tensor(X_train[train_idx],dtype=torch.long), torch.tensor(y[train_idx],dtype=torch.long))
    valid_dataset = torch.utils.data.TensorDataset(torch.tensor(X_train[val_idx],dtype=torch.long), torch.tensor(y[val_idx],dtype=torch.long))
    tq = tqdm(range(args.epochs + 1))
    for child in tsfm.children():
        for param in child.parameters():
            if not param.requires_grad:
                print("whoopsies")
            param.requires_grad = False
    frozen = True
    for epoch in tq:
        if epoch > 0 and frozen:
            for child in tsfm.children():
                for param in child.parameters():
                    param.requires_grad = True
            frozen = False
#             del scheduler0
            torch.cuda.empty_cache()
        train_preds = []
        val_preds = []
        train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=args.batch_size, shuffle=False)
        valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=args.batch_size, shuffle=False)
        avg_loss = 0.
        avg_accuracy = 0.
        optimizer.zero_grad()
        pbar = tqdm(enumerate(train_loader),total=len(train_loader),leave=False)
        for i,(x_batch, y_batch) in pbar:
            model_bert.train()
            y_pred = model_bert(x_batch.cuda(), attention_mask=(x_batch>0).cuda())
            loss =  F.binary_cross_entropy_with_logits(y_pred.view(-1).cuda(),y_batch.float().cuda())
            loss = loss.mean()
            loss.backward()
            if i % args.accumulation_steps == 0 or i == len(pbar) - 1:
                optimizer.step()
                optimizer.zero_grad()
                if not frozen:
                    scheduler.step()
                else:
                    scheduler0.step()
            lossf = loss.item()
            pbar.set_postfix(loss = lossf)
            avg_loss += loss.item() / len(train_loader)
            y_pred = model_bert(x_batch.cuda(), attention_mask=(x_batch>0).cuda())
            y_pred = y_pred.squeeze().detach().cpu().numpy()
            train_preds = np.concatenate([train_preds, np.atleast_1d(y_pred)])
        train_preds = sigmoid(train_preds)
#         print(train_preds)
        model_bert.eval()
        pbar = tqdm(enumerate(valid_loader),total=len(valid_loader),leave=False)
        for i,(x_batch, y_batch) in pbar:
            y_pred = model_bert(x_batch.cuda(), attention_mask=(x_batch>0).cuda())
            y_pred = y_pred.squeeze().detach().cpu().numpy()
            val_preds = np.concatenate([val_preds, np.atleast_1d(y_pred)])
        val_preds = sigmoid(val_preds)
        print(val_preds)
        best_th = 0
        socre_train = f1_score(y[train_idx], train_preds > 0.5)
        score = f1_score(y[val_idx], val_preds > 0.5)
        print(f"\nAUC = {roc_auc_score(y[train_idx], train_preds):.4f}, F1 score @0.5 = {socre_train:.4f}")
        print(f"\nAUC = {roc_auc_score(y[val_idx], val_preds):.4f}, F1 score @0.5 = {score:.4f}")
        if score >= best_score:
            print("Saving model")
            torch.save(model_bert.state_dict(),os.path.join(args.ckpt_path, f"model_{fold}.bin"))
            best_score = score

  0%|          | 0/15 [00:00<?, ?it/s]/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha)

  0%|          | 0/15 [00:00<?, ?it/s, loss=0.708]

Training for fold 0



 93%|█████████▎| 14/15 [00:01<00:00,  7.81it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 17.32it/s]
                                             

[0.55658928 0.5791961  0.57537051 0.51060704 0.56624914 0.5725307
 0.57666678 0.55765698 0.57896699 0.55583484 0.58350795 0.55969614
 0.54995509 0.57705326 0.57311966 0.553829   0.57311311 0.57459753
 0.58331793 0.57396458 0.41832551 0.56030665 0.56102739 0.57284095
 0.5539243  0.55325598 0.54274442 0.57275263 0.56920565 0.56306136
 0.57756993 0.55555955 0.54500727 0.56517888 0.54339151 0.57555735
 0.56380773 0.56328184 0.56146927 0.55635234 0.57709602 0.56673967
 0.5419765  0.55646711 0.55930055 0.56645025 0.56147557 0.57400188
 0.53069344 0.55368736 0.56343803 0.49640356 0.56825565 0.56318058
 0.5627879  0.53942873 0.57457324 0.57520445 0.5540418  0.58038353
 0.58074751 0.5572515  0.58408241 0.56468493 0.56972357 0.48819147
 0.53998823 0.55581108 0.56946639 0.55233273 0.5595697  0.57517564
 0.57151102 0.55975363 0.5665622  0.56411162 0.57601136 0.56259063
 0.56985438 0.44838721 0.58009639 0.56990031 0.58375678 0.55810913
 0.56565436 0.56650465]

AUC = 0.4477, F1 score @0.5 = 0.7551



100%|██████████| 15/15 [00:03<00:00,  4.78it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 17.04it/s]
                                             

[0.55659085 0.57879924 0.57486419 0.51069137 0.56630297 0.57259256
 0.57637257 0.55738841 0.57874294 0.55589448 0.58327501 0.55950285
 0.54995377 0.57685695 0.57291629 0.5541154  0.57277583 0.57481482
 0.58303572 0.57358719 0.41838991 0.56012626 0.56095728 0.57262767
 0.55393471 0.55273876 0.54250592 0.57226944 0.57030486 0.56283189
 0.57718946 0.55540419 0.54496169 0.56506157 0.54338938 0.57484471
 0.56403192 0.5629031  0.56134393 0.55645485 0.57666044 0.56666884
 0.5415329  0.55603694 0.55903217 0.56654395 0.56139942 0.57368878
 0.53080155 0.55343167 0.56307233 0.49666867 0.56777812 0.56273593
 0.56243202 0.53931889 0.57437872 0.57519292 0.55393112 0.58017019
 0.58051401 0.55684952 0.58394321 0.56441447 0.56987847 0.48828754
 0.540172   0.55569491 0.56966275 0.55246921 0.55923769 0.57499386
 0.57169656 0.55974432 0.56642651 0.56380512 0.57611309 0.5625415
 0.56989009 0.44834907 0.58011978 0.56996011 0.58353461 0.55803926
 0.56546272 0.56631031]

AUC = 0.4493, F1 score @0.5 = 0.7551



100%|██████████| 15/15 [00:03<00:00,  4.77it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 17.00it/s]
                                             

[0.55703902 0.57910493 0.57506954 0.51076935 0.56667447 0.57294949
 0.57667877 0.55766711 0.57888178 0.55628509 0.58337233 0.5595725
 0.55029608 0.57710352 0.57306506 0.55468161 0.57293395 0.57521145
 0.58320039 0.57381475 0.41848891 0.56057142 0.56139396 0.5728624
 0.55429427 0.55300404 0.54297309 0.57256149 0.57062744 0.56298568
 0.57740132 0.55579055 0.54542192 0.56524188 0.54385689 0.57519899
 0.56441383 0.5630929  0.56170173 0.55676791 0.57683871 0.56694689
 0.54188569 0.55626879 0.559457   0.56683063 0.56182697 0.57386797
 0.53088679 0.55364142 0.56328515 0.49685296 0.56799552 0.56302591
 0.56267671 0.53983431 0.57468394 0.57543146 0.55426211 0.58029847
 0.58066004 0.55703035 0.58429394 0.56461931 0.56995704 0.48837606
 0.54077983 0.55595842 0.57000561 0.55288314 0.55952388 0.57536051
 0.57205426 0.55990012 0.56673383 0.56392866 0.57630103 0.56296364
 0.57017714 0.44846055 0.58043653 0.57030922 0.58373966 0.55812969
 0.565766   0.56648093]

AUC = 0.4492, F1 score @0.5 = 0.7551

A

100%|██████████| 15/15 [00:03<00:00,  4.75it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 17.07it/s]
                                             

[0.55782846 0.57961764 0.57543644 0.51091315 0.56733573 0.57354277
 0.57722791 0.5581758  0.57914124 0.55695891 0.58358385 0.55974988
 0.55088745 0.57756268 0.57335319 0.55574777 0.57323986 0.57591942
 0.58351964 0.57421257 0.41867047 0.56134684 0.56216138 0.57329311
 0.55493065 0.55349444 0.54380365 0.57307431 0.5712382  0.56328921
 0.57782556 0.55642354 0.54622796 0.56556258 0.54464758 0.57586522
 0.56508636 0.56343534 0.56233279 0.55733215 0.57717874 0.56741885
 0.5424815  0.55669477 0.56018586 0.56733368 0.56256113 0.57420256
 0.53104495 0.55402885 0.5636872  0.49726157 0.56831311 0.56356858
 0.56308811 0.54073336 0.57522059 0.57582548 0.55483201 0.58057881
 0.58097075 0.5573583  0.58488029 0.56500006 0.57015301 0.48853976
 0.54176254 0.55642487 0.57063024 0.55361312 0.56003782 0.57601065
 0.57268785 0.56012112 0.56724968 0.5641915  0.57666168 0.56369681
 0.57067425 0.44865856 0.58097982 0.57090901 0.58408522 0.5582785
 0.56630691 0.56680864]

AUC = 0.4507, F1 score @0.5 = 0.7551



100%|██████████| 15/15 [00:03<00:00,  4.71it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.79it/s]
                                             

[0.5589864  0.58037391 0.57598299 0.51111897 0.56831879 0.57442598
 0.57803355 0.55894244 0.5795121  0.55798274 0.58388947 0.55997408
 0.55177146 0.57823492 0.57380116 0.55723043 0.57368507 0.57692763
 0.58399824 0.57480339 0.41893153 0.5624412  0.56326547 0.57389689
 0.55588894 0.55421119 0.54504164 0.57382754 0.57204243 0.56374635
 0.57843806 0.55735823 0.54739347 0.56601731 0.54583989 0.57687185
 0.56607222 0.56391902 0.56324124 0.55814775 0.57767634 0.56813192
 0.54327197 0.55733095 0.56125918 0.56807688 0.56365713 0.57469358
 0.53127107 0.55458135 0.56428066 0.49771353 0.56879651 0.56434595
 0.56370762 0.54206485 0.57600332 0.57638308 0.55566122 0.58100267
 0.58141794 0.55785023 0.585772   0.56555263 0.57036654 0.48877609
 0.54326806 0.55711398 0.57154014 0.55468848 0.56079305 0.57696167
 0.57361449 0.56047704 0.56799117 0.56458024 0.5771484  0.56478009
 0.57141085 0.44897835 0.58179564 0.57181215 0.58461568 0.55850789
 0.56708612 0.56726915]

AUC = 0.4510, F1 score @0.5 = 0.7551


100%|██████████| 15/15 [00:03<00:00,  4.67it/s, loss=0.666]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.74it/s]
                                             

[0.56043314 0.58134988 0.57667966 0.51137935 0.56955197 0.57552765
 0.57904317 0.55990924 0.5799781  0.55929037 0.58426284 0.560209
 0.55287829 0.57907176 0.57436429 0.55897435 0.57423783 0.57815605
 0.58459184 0.5755761  0.41926367 0.5637764  0.56462699 0.57464103
 0.5570886  0.55509359 0.54660222 0.57478038 0.57296321 0.56432017
 0.57917263 0.55853875 0.54885856 0.56658814 0.54736708 0.57810585
 0.56728056 0.56452686 0.56435866 0.55914681 0.57830279 0.56903677
 0.54424845 0.55813037 0.56263426 0.56898402 0.56506066 0.57530707
 0.53155658 0.55526573 0.56501491 0.49812583 0.56946097 0.56529084
 0.56451802 0.5437597  0.57695062 0.57705112 0.5567024  0.58151431
 0.58195753 0.55848392 0.58692219 0.56625185 0.57052087 0.48907625
 0.54523307 0.55797402 0.57265887 0.55602613 0.56172573 0.57815535
 0.57475339 0.56086115 0.56894304 0.56505734 0.57766518 0.56615296
 0.57230358 0.44940133 0.58282031 0.57294569 0.58529306 0.5588377
 0.56804791 0.56781625]

AUC = 0.4514, F1 score @0.5 = 0.7551

AU

100%|██████████| 15/15 [00:03<00:00,  4.71it/s, loss=0.665]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.79it/s]
                                             

[0.56214333 0.58250759 0.57750403 0.5116893  0.57099067 0.5768015
 0.58021132 0.56104713 0.5805265  0.56082327 0.58469018 0.56046446
 0.55415825 0.58003666 0.57501527 0.56100409 0.57487571 0.57958141
 0.58527412 0.57647128 0.41966089 0.565319   0.56622352 0.57548899
 0.55847039 0.55612781 0.54844012 0.57591133 0.574      0.56496743
 0.58001864 0.5599099  0.5505943  0.56725266 0.54916142 0.57951155
 0.56866478 0.56524961 0.56565224 0.5602931  0.57903499 0.57009355
 0.54539717 0.55907179 0.56423932 0.57001496 0.56671552 0.57602506
 0.53189514 0.55606184 0.56587018 0.49866541 0.57029927 0.56638827
 0.5654852  0.54576988 0.57798742 0.57781309 0.55792694 0.58207668
 0.58256772 0.55922532 0.58825784 0.56706565 0.57064599 0.48943212
 0.54758105 0.55896662 0.57395049 0.55759397 0.56281921 0.57955993
 0.57607108 0.56145686 0.57005849 0.56559912 0.57817472 0.56777747
 0.57329822 0.44989784 0.58400085 0.57425766 0.58608378 0.55921968
 0.56916563 0.56842439]

AUC = 0.4528, F1 score @0.5 = 0.7551



100%|██████████| 15/15 [00:03<00:00,  4.63it/s, loss=0.665]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.90it/s]
                                             

[0.56405212 0.58379737 0.57842834 0.51203936 0.57259308 0.57813594
 0.58149032 0.56233399 0.58113541 0.56256197 0.58518189 0.56070451
 0.55556237 0.58113156 0.57577144 0.56311484 0.57558801 0.58111676
 0.58604303 0.57750152 0.42011804 0.5669701  0.56797223 0.57642448
 0.5599998  0.5572592  0.55052706 0.57717674 0.57509634 0.56569895
 0.5809576  0.56140293 0.55252416 0.56797001 0.55118563 0.58108413
 0.57015114 0.56604162 0.56705757 0.56153235 0.57987898 0.57126753
 0.54664502 0.56013724 0.56604848 0.57112459 0.56858835 0.5768282
 0.53227838 0.55694215 0.56682828 0.49875056 0.5712337  0.56759661
 0.56658059 0.54805133 0.57904848 0.5785769  0.55928066 0.5827296
 0.5832575  0.56006612 0.58976245 0.56798892 0.57063723 0.48983798
 0.5502489  0.56005597 0.57537075 0.55932491 0.56401846 0.58113187
 0.57750616 0.56187311 0.5713015  0.56622564 0.57854242 0.56960294
 0.5743047  0.45048082 0.58529063 0.57570408 0.58695791 0.55967253
 0.57039557 0.56905293]

AUC = 0.4537, F1 score @0.5 = 0.7551

A

100%|██████████| 15/15 [00:03<00:00,  4.63it/s, loss=0.665]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.74it/s]
                                             

[0.56609405 0.58519595 0.57941988 0.51242631 0.57429236 0.57944774
 0.58280999 0.56371544 0.5817986  0.56443552 0.58571598 0.56095675
 0.55702996 0.58230663 0.576603   0.56521601 0.57635529 0.58271977
 0.58686271 0.57861874 0.4206224  0.56868043 0.56981574 0.57740847
 0.56159378 0.55845631 0.55277666 0.57853696 0.57619786 0.56650107
 0.58195014 0.56296891 0.55459251 0.56872986 0.55335745 0.58270969
 0.57165899 0.56689961 0.56853073 0.56281307 0.58079397 0.57251696
 0.54797508 0.56129103 0.56798382 0.57225692 0.57060954 0.57769776
 0.53270237 0.55788958 0.56785251 0.49880868 0.57228034 0.5688749
 0.56777463 0.55052266 0.58005623 0.57933426 0.56072448 0.58342244
 0.5839996  0.56099062 0.59137537 0.56899396 0.57051419 0.49028784
 0.55315284 0.56119414 0.57685677 0.56114779 0.56528041 0.58280666
 0.57899791 0.56244377 0.57263887 0.56690773 0.57869274 0.57156584
 0.57524248 0.45113932 0.58662248 0.57720871 0.58788149 0.56020825
 0.5716929  0.56967636]

AUC = 0.4557, F1 score @0.5 = 0.7551



100%|██████████| 15/15 [00:03<00:00,  4.68it/s, loss=0.664]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.69it/s]
                                             

[0.56826389 0.5866689  0.58046682 0.51284802 0.57606004 0.58073174
 0.58413146 0.56517745 0.58251172 0.56639628 0.58628556 0.56128599
 0.55854365 0.5835377  0.57748894 0.56749705 0.57716797 0.58440175
 0.58772228 0.57976397 0.42117086 0.57045594 0.57175601 0.57841379
 0.56321024 0.55972715 0.55514382 0.57998118 0.57733964 0.56734241
 0.58300469 0.56457904 0.55678441 0.56952653 0.55561103 0.58435387
 0.57318094 0.56781934 0.57006712 0.56413842 0.58175958 0.57381939
 0.54938285 0.56252043 0.5699815  0.57340944 0.57273033 0.57862722
 0.53316326 0.55889685 0.56893369 0.49912714 0.57343475 0.57022401
 0.56903607 0.55314461 0.58098626 0.58012246 0.56224594 0.58412887
 0.58478457 0.56196799 0.59303326 0.57005146 0.57040873 0.4907756
 0.55621719 0.56235921 0.57839738 0.56305206 0.56660578 0.58456011
 0.58054933 0.56307001 0.57402855 0.56762797 0.57870813 0.5736458
 0.57611102 0.45184845 0.58797007 0.57874543 0.58883069 0.56077411
 0.57304888 0.57029625]

AUC = 0.4591, F1 score @0.5 = 0.7551

A

100%|██████████| 15/15 [00:03<00:00,  4.63it/s, loss=0.664]
                                                           
100%|██████████| 4/4 [00:00<00:00, 16.66it/s]
                                             

[0.57053584 0.58817157 0.58154691 0.51330051 0.57788377 0.58196127
 0.58543231 0.56671881 0.58326575 0.56842462 0.5869062  0.56174005
 0.56009607 0.58481841 0.57845084 0.5699164  0.57802498 0.58614827
 0.58864016 0.58090571 0.42175745 0.57226579 0.57375853 0.57942159
 0.56484637 0.56106786 0.55760026 0.58148465 0.57854001 0.56823744
 0.58413603 0.56619531 0.55904916 0.57034328 0.55790262 0.58602287
 0.57471136 0.56878018 0.57164544 0.56550742 0.58277211 0.5751583
 0.5508154  0.56382517 0.57199212 0.57458508 0.57491364 0.57961257
 0.53365801 0.55995463 0.57007516 0.49955618 0.57462553 0.57164231
 0.57032941 0.55587048 0.58184729 0.58093945 0.56381592 0.58487239
 0.58563438 0.56298999 0.59471037 0.5711461  0.57039419 0.49129795
 0.55937176 0.5635378  0.57999246 0.56501672 0.56798041 0.58635725
 0.58215667 0.56375818 0.57542311 0.56840792 0.57868929 0.57581099
 0.57693604 0.45261967 0.58933073 0.58030846 0.58978282 0.56135387
 0.57445317 0.57091998]

AUC = 0.4613, F1 score @0.5 = 0.7523



100%|██████████| 15/15 [00:03<00:00,  4.64it/s, loss=0.664]
                                                           
  0%|          | 0/15 [00:00<?, ?it/s]

[0.57283994 0.58969934 0.58265844 0.51378184 0.57969608 0.58314813
 0.58668209 0.56828497 0.58405628 0.57045334 0.58755129 0.56231926
 0.56165074 0.58611176 0.57943555 0.57239121 0.57890671 0.58790631
 0.58957844 0.58204714 0.42238205 0.57406753 0.57577332 0.5804223
 0.56644694 0.56242633 0.56005734 0.58301891 0.57974522 0.56914587
 0.58528681 0.56780432 0.56134074 0.57118208 0.56017397 0.58762165
 0.57620607 0.56978117 0.57322868 0.56688319 0.58380861 0.57650984
 0.55228681 0.56515973 0.57399042 0.57574817 0.57710195 0.58063254
 0.53418375 0.5610423  0.57122625 0.50009703 0.57589103 0.57306954
 0.57165292 0.55862988 0.58262064 0.58180015 0.56541261 0.5856045
 0.58650659 0.56403778 0.59639158 0.57226181 0.57048061 0.49185214
 0.56254624 0.56469119 0.58156574 0.56695998 0.56934409 0.58815091
 0.58375775 0.56452206 0.57683125 0.56920725 0.57868168 0.57801277
 0.5777192  0.45342629 0.59066958 0.58184381 0.59073118 0.56197672
 0.57586816 0.57153805]

AUC = 0.4634, F1 score @0.5 = 0.7523

A


100%|██████████| 15/15 [00:03<00:00,  4.63it/s, loss=0.664]
                                                           
  0%|          | 0/15 [00:00<?, ?it/s]

[0.57517252 0.59121184 0.58377744 0.51428908 0.58151785 0.58431788
 0.58790647 0.56989294 0.58487687 0.57249146 0.5882487  0.56305277
 0.56322467 0.58742867 0.58048583 0.57490712 0.57982196 0.58969249
 0.59057655 0.58316198 0.42303919 0.57586073 0.57779114 0.58140652
 0.56804791 0.5638199  0.56251559 0.58457453 0.58100109 0.57009799
 0.58649627 0.56938324 0.563627   0.57203492 0.56240951 0.58919978
 0.57770984 0.57080366 0.57482073 0.56829353 0.58487492 0.57787315
 0.55373804 0.56654493 0.57594585 0.57693375 0.5792809  0.58169297
 0.53473813 0.56215876 0.57240825 0.50068012 0.57713712 0.57453211
 0.57297346 0.56139374 0.58336458 0.58271349 0.56702052 0.58636403
 0.58744357 0.56511248 0.59806799 0.57339024 0.57075719 0.4924352
 0.56568427 0.56583522 0.58316122 0.5689041  0.57070036 0.58992974
 0.58538509 0.56530288 0.57820579 0.57006506 0.57884231 0.58023845
 0.57854838 0.45428631 0.59202324 0.58338363 0.59166055 0.56262004
 0.57730485 0.57218507]

AUC = 0.4665, F1 score @0.5 = 0.7523




100%|██████████| 15/15 [00:03<00:00,  4.59it/s, loss=0.663]
                                                           
  0%|          | 0/15 [00:00<?, ?it/s]

[0.57746215 0.59272534 0.58492391 0.51482127 0.58328495 0.58551967
 0.5890927  0.57147924 0.58572509 0.5744698  0.5889571  0.56389638
 0.5647856  0.58872859 0.58152707 0.57738203 0.58075246 0.59145538
 0.59158181 0.58426654 0.42372984 0.57761419 0.57977698 0.58237644
 0.56959717 0.56519113 0.5648894  0.58612969 0.58224211 0.57104087
 0.58769445 0.57093771 0.56588269 0.57290999 0.56456768 0.59067521
 0.57918832 0.57185728 0.57639098 0.56969762 0.58594426 0.57922843
 0.55520519 0.56792247 0.57785278 0.57810528 0.58140229 0.5827724
 0.53531878 0.56328526 0.57356301 0.50133755 0.57843959 0.57595955
 0.57430381 0.56410178 0.5840682  0.58369811 0.56862873 0.58708732
 0.5883823  0.56619182 0.59973701 0.57452156 0.57119676 0.49304512
 0.56874245 0.56693885 0.58470354 0.57078232 0.57199186 0.59165766
 0.58697272 0.566158   0.57957487 0.57092255 0.57915742 0.58244372
 0.5794202  0.45516568 0.59335481 0.58487429 0.59258695 0.56331887
 0.57872492 0.57285227]

AUC = 0.4679, F1 score @0.5 = 0.7523




100%|██████████| 15/15 [00:03<00:00,  4.59it/s, loss=0.663]
                                                           
  0%|          | 0/15 [00:00<?, ?it/s]

[0.57974522 0.59419478 0.58605591 0.5153744  0.58507023 0.58677645
 0.59031206 0.57309658 0.58659608 0.57644151 0.58972723 0.56487091
 0.56637131 0.5900429  0.58263864 0.57983322 0.58171448 0.59325561
 0.59266739 0.58533112 0.42444693 0.57935542 0.58174867 0.58332658
 0.57117211 0.5665899  0.56722756 0.58769062 0.58355268 0.5720323
 0.58895523 0.57245155 0.56809467 0.57380507 0.56666403 0.59213971
 0.58071843 0.57291861 0.5779659  0.57114638 0.58703755 0.58058691
 0.55661689 0.56934588 0.57969227 0.57932888 0.58348304 0.58388503
 0.53592341 0.56443033 0.57474484 0.50201591 0.5796591  0.57742093
 0.57560787 0.56675325 0.58483463 0.58475738 0.5702273  0.58784229
 0.5893981  0.56728936 0.60140541 0.57565564 0.57188227 0.49367947
 0.5716899  0.56805567 0.58629852 0.57267968 0.57325524 0.59336306
 0.58860722 0.56699795 0.58088526 0.57185041 0.57978539 0.58464107
 0.58043697 0.45609897 0.59473984 0.58639382 0.59348673 0.56403295
 0.58016324 0.57358967]

AUC = 0.4707, F1 score @0.5 = 0.7523




100%|██████████| 15/15 [00:03<00:00,  4.61it/s, loss=0.662]
                                                           
100%|██████████| 16/16 [01:07<00:00,  4.21s/it]A

[0.58193859 0.59566415 0.58722305 0.51594945 0.58679268 0.58813045
 0.59152398 0.57465737 0.58748816 0.57832261 0.59049008 0.56589831
 0.56793722 0.59132234 0.5837087  0.58218255 0.58268439 0.59502408
 0.59374225 0.58639042 0.42519301 0.58104451 0.58367385 0.58426897
 0.57269304 0.56793807 0.56944419 0.58923384 0.5848275  0.57299284
 0.59017975 0.57394583 0.57025597 0.57472571 0.56866872 0.5934991
 0.58223795 0.57400913 0.57950871 0.57257962 0.58811513 0.58192733
 0.55804492 0.57073108 0.5814772  0.58054066 0.58548282 0.58500364
 0.53655076 0.56557185 0.57587571 0.5027561  0.58093779 0.57881783
 0.57691784 0.56929807 0.58560707 0.58590249 0.571816   0.588551
 0.59039197 0.56837578 0.6030687  0.5767835  0.57271764 0.49433606
 0.57450921 0.56913924 0.58783949 0.57451577 0.5744375  0.59501121
 0.5901933  0.56792186 0.58219054 0.57275204 0.58058912 0.58678091
 0.58153101 0.45703487 0.59610267 0.58786048 0.59439659 0.56481402
 0.58156876 0.57436109]

AUC = 0.4736, F1 score @0.5 = 0.7523

AU

In [10]:
# Need get false prediction
# https://stackoverflow.com/questions/34698161/how-to-interpret-almost-perfect-accuracy-and-auc-roc-but-zero-f1-score-precisio